// Auth posture for CONTROLLED_PRODUCTION through the Management API.
// Dry-run prints the diff; --apply patches only the listed keys.
//
// Decisions:
//  - site_url / redirects: only the dedicated Pages host (links land in /cuenta/);
//  - anonymous sign-ins ON: customers get a session when they save their data;
//  - signup stays enabled because GoTrue also gates anonymous sign-ins with it;
//    a new identity gets NO role (roles only via request/approval);
//  - email confirmation required and no SMTP: team onboarding uses one-time
//    links generated by the operator (scripts/controlled-production/accounts.mjs);
//  - 12+ character passwords, leaked-password check (HIBP);
//  - mail templates use token_hash + SiteURL (never ConfirmationURL).
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { NON_CP_REFS } from './target-keys.mjs';

const ROOT = path.resolve(import.meta.dirname, '../..');
const SITE = 'https://la-taba-commercial-pilot.pages.dev';
const MAILS = [
  ['confirmation.html', 'mailer_templates_confirmation_content', 'mailer_subjects_confirmation', 'Confirmá tu cuenta de La Taba'],
  ['recovery.html', 'mailer_templates_recovery_content', 'mailer_subjects_recovery', 'Cambiá tu contraseña de La Taba'],
  ['email_change.html', 'mailer_templates_email_change_content', 'mailer_subjects_email_change', 'Confirmá tu correo nuevo en La Taba'],
  ['magic_link.html', 'mailer_templates_magic_link_content', 'mailer_subjects_magic_link', 'Tu enlace para entrar a La Taba'],
  ['invite.html', 'mailer_templates_invite_content', 'mailer_subjects_invite', 'Te invitaron a trabajar en La Taba'],
  ['reauthentication.html', 'mailer_templates_reauthentication_content', 'mailer_subjects_reauthentication', 'Tu código de verificación de La Taba'],
];

export function desiredAuthConfig() {
  const desired = {
    site_url: SITE,
    uri_allow_list: `${SITE}/**`,
    disable_signup: false,
    external_anonymous_users_enabled: true,
    external_email_enabled: true,
    mailer_autoconfirm: false,
    password_min_length: 12,
    password_hibp_enabled: true,
    refresh_token_rotation_enabled: true,
    external_phone_enabled: false,
  };
  for (const [file, contentKey, subjectKey, subject] of MAILS) {
    const body = readFileSync(path.join(ROOT, 'supabase', 'templates', file), 'utf8').trim();
    assert.ok(!/\{\{\s*\.ConfirmationURL\s*\}\}/.test(body), `TEMPLATE_USES_CONFIRMATION_URL:${file}`);
    desired[contentKey] = body;
    desired[subjectKey] = subject;
  }
  return desired;
}

async function main(args) {
  const ref = args[args.indexOf('--ref') + 1];
  assert.match(ref || '', /^[a-z0-9]{20}$/, 'REF_REQUIRED');
  assert.ok(!NON_CP_REFS.has(ref), 'AUTH_CONFIG_IS_FOR_CONTROLLED_PRODUCTION_ONLY');
  const token = process.env.SUPABASE_ACCESS_TOKEN;
  assert.ok(token, 'SUPABASE_ACCESS_TOKEN_REQUIRED');
  const url = `https://api.supabase.com/v1/projects/${ref}/config/auth`;
  const headers = { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' };
  const current = await (await fetch(url, { headers })).json();
  const desired = desiredAuthConfig();
  const diff = Object.fromEntries(Object.entries(desired).filter(([k, v]) => current[k] !== v)
    .map(([k, v]) => [k, k.includes('_content') ? 'template' : { from: current[k], to: v }]));
  if (!args.includes('--apply')) { console.log(JSON.stringify({ dryRun: true, ref, diff }, null, 1)); return; }
  const response = await fetch(url, { method: 'PATCH', headers, body: JSON.stringify(desired) });
  assert.ok(response.ok, `AUTH_PATCH_HTTP_${response.status}:${(await response.text()).slice(0, 200)}`);
  const after = await (await fetch(url, { headers })).json();
  const mismatched = Object.keys(desired).filter((k) => after[k] !== desired[k]);
  assert.deepEqual(mismatched, [], `AUTH_CONFIG_NOT_APPLIED:${mismatched.join(',')}`);
  console.log(JSON.stringify({ applied: true, ref, changed: Object.keys(diff) }, null, 1));
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(fileURLToPath(import.meta.url))) {
  main(process.argv.slice(2)).catch((error) => { console.error(`AUTH_CONFIG_BLOCKED:${error.message}`); process.exitCode = 1; });
}
