begin;
create extension if not exists pgtap;
select plan(16);
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000001',true);
select lives_ok($$select public.create_manual_catalog_product_draft('20000000-0000-4000-8000-000000000001','commerce-test-001')$$,'owner can create a manual draft');
select is((select count(*)::int from catalog_product_drafts),1,'one draft created');
select lives_ok($$select public.create_manual_catalog_product_draft('20000000-0000-4000-8000-000000000001','commerce-test-001')$$,'retry is idempotent');
select is((select count(*)::int from catalog_product_drafts),1,'retry did not duplicate');
select throws_ok($$select public.create_manual_catalog_product_draft('20000000-0000-4000-8000-000000000002','commerce-test-002')$$,'42501','No podés crear productos en este negocio.','other business denied');
select lives_ok($$select public.save_catalog_product_draft_details((select id from catalog_product_drafts limit 1),'{"name":"Producto de prueba","category":"Carnes","pricingMode":"variable_weight","unitQuantity":"0.25","pricePerKg":"","stock":""}')$$,'unknown commercial data remains blank');
select is((select status from catalog_product_drafts limit 1),'pending_review','saving never publishes');
select is((select commercial_details->>'stock' from catalog_product_drafts limit 1),'','unknown stock is not zero');
select throws_ok($$update catalog_product_drafts set status='approved'$$,'23514','Completá el código real del producto antes de revisar la publicación.','manual draft cannot publish without a code');
select lives_ok($$select public.bind_catalog_product_draft_code((select id from catalog_product_drafts limit 1),'7790895000997')$$,'real valid GTIN can be bound');
select throws_ok($$update catalog_product_drafts set status='approved'$$,'23514','La venta por peso variable necesita un circuito de pesaje y cobro. Guardá el borrador sin publicar.','variable weight cannot become a unit sale');
select throws_ok($$select public.save_catalog_product_draft_details((select id from catalog_product_drafts limit 1),'{"available":true}')$$,'22023','Revisá los datos del borrador.','publication flags cannot be injected');
select throws_ok($$select public.save_catalog_product_draft_details((select id from catalog_product_drafts limit 1),'{"price":"-1"}')$$,'22023','Revisá cantidades e importes.','negative price rejected');
select throws_ok($$select public.save_catalog_product_draft_details((select id from catalog_product_drafts limit 1),'{"stock":"1.5"}')$$,'22023','El stock de envases y las unidades son enteros.','fractional package stock rejected');
select set_config('request.jwt.claim.sub','10000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.save_catalog_product_draft_details((select id from catalog_product_drafts limit 1),'{}')$$,'42501','No podés editar este borrador.','other user cannot edit');
set local role authenticated;
select is((select count(*)::int from catalog_product_drafts),0,'RLS hides drafts of other business');
reset role;
select * from finish();
rollback;
