-- TABA production seed
--
-- Intentionally empty. `supabase db reset` must not invent a business,
-- address, beverage identity, price, image or stock.
--
-- Load real commercial data only after validating it with the business, then
-- complete every required master-catalog field and set `is_verified` /
-- `available` through an authenticated owner/admin/staff workflow.
