// Catálogo de demostración del comercio demo (La Taba Pizzería) para PedidoPropio.
// Precios en ARS, estimados de mercado argentino y editables desde el panel.
// Cada producto lleva `image` (foto real licenciada, ver docs/image-sources.md);
// los `tone` quedan como respaldo tonal para productos creados desde el panel.
//
// Categorías:
//  - Pizzas, Combos, Promos y Bebidas replican la vidriera de la maqueta comercial.
// Nota legal: no se incluyen bebidas alcohólicas. "Bebidas" es una categoría segura.
export const categories = [
  { id: 'all', name: 'Todos' },
  { id: 'pizzas', name: 'Pizzas' },
  { id: 'combos', name: 'Combos' },
  { id: 'promos', name: 'Promos' },
  { id: 'bebidas', name: 'Bebidas' },
];

const MARKET_NOTE = 'El local confirma disponibilidad antes de preparar tu pedido.';

export const products = [
  // ===== Pizzas =====
  {
    id: 'p-muzzarella',
    name: 'Muzzarella',
    description: 'La clásica de la casa: muzzarella fundida, salsa de tomate y orégano.',
    categoryId: 'pizzas',
    tone: 'pizza',
    image: 'assets/products/pizza-muzzarella.webp',
    price: 8990,
    stock: 14,
    available: true,
    featured: true,
    popular: true,
    badge: 'Más pedida',
    unit: 'unidad',
    unitLabel: 'Grande · 8 porciones',
    marketNote: MARKET_NOTE,
    prepMinutes: 18,
  },
  {
    id: 'p-especial',
    name: 'Especial',
    description: 'Muzzarella, jamón, aceitunas y un toque de rúcula fresca al salir del horno.',
    categoryId: 'pizzas',
    tone: 'pizza',
    image: 'assets/products/pizza-especial.webp',
    price: 10490,
    stock: 10,
    available: true,
    featured: true,
    popular: true,
    unit: 'unidad',
    unitLabel: 'Grande · 8 porciones',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },
  {
    id: 'p-fugazzeta',
    name: 'Fugazzeta',
    description: 'Cebolla dulce, doble muzzarella y orégano sobre masa media masa.',
    categoryId: 'pizzas',
    tone: 'pizza',
    image: 'assets/products/pizza-fugazzeta.webp',
    price: 9490,
    stock: 8,
    available: true,
    featured: true,
    popular: true,
    unit: 'unidad',
    unitLabel: 'Grande · 8 porciones',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },
  {
    id: 'p-napolitana',
    name: 'Napolitana',
    description: 'Rodajas de tomate fresco, ajo, muzzarella y albahaca del día.',
    categoryId: 'pizzas',
    tone: 'pizza',
    image: 'assets/products/pizza-napolitana.webp',
    price: 9990,
    stock: 4,
    available: true,
    featured: false,
    popular: true,
    unit: 'unidad',
    unitLabel: 'Grande · 8 porciones',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },
  {
    id: 'p-pepperoni',
    name: 'Pepperoni',
    description: 'Pepperoni levemente picante sobre base de muzzarella bien fundida.',
    categoryId: 'pizzas',
    tone: 'pizza',
    image: 'assets/products/pizza-pepperoni.webp',
    price: 11490,
    stock: 7,
    available: true,
    featured: true,
    popular: false,
    unit: 'unidad',
    unitLabel: 'Grande · 8 porciones',
    marketNote: MARKET_NOTE,
    prepMinutes: 22,
  },
  {
    id: 'p-calabresa',
    name: 'Calabresa',
    description: 'Longaniza calabresa, muzzarella y aceitunas: sabor fuerte de pizzería.',
    categoryId: 'pizzas',
    tone: 'pizza',
    image: 'assets/products/pizza-calabresa.webp',
    price: 10990,
    stock: 3,
    available: true,
    featured: false,
    popular: true,
    unit: 'unidad',
    unitLabel: 'Grande · 8 porciones',
    marketNote: MARKET_NOTE,
    prepMinutes: 22,
  },
  {
    id: 'p-jamon-muzzarella',
    name: 'Jamón y muzzarella',
    description: 'Jamón cocido natural y muzzarella cremosa, directo de la piedra.',
    categoryId: 'pizzas',
    tone: 'pizza',
    image: 'assets/products/pizza-jamon.webp',
    price: 10290,
    stock: 11,
    available: true,
    featured: false,
    popular: false,
    unit: 'unidad',
    unitLabel: 'Grande · 8 porciones',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },

  // ===== Combos =====
  {
    id: 'p-combo-familiar',
    name: 'Combo familiar',
    description: '3 pizzas grandes a elección y 2 gaseosas 1.5 L para toda la mesa.',
    categoryId: 'combos',
    tone: 'combo',
    image: 'assets/products/combo-familiar.webp',
    price: 27990,
    oldPrice: 32460,
    stock: 6,
    available: true,
    featured: true,
    popular: true,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: '3 grandes + 2 gaseosas',
    marketNote: MARKET_NOTE,
    prepMinutes: 30,
  },
  {
    id: 'p-combo-pizza-bebida',
    name: 'Combo pizza + bebida',
    description: 'Muzzarella grande con gaseosa 1.5 L bien fría. Resuelve la cena.',
    categoryId: 'combos',
    tone: 'combo',
    image: 'assets/products/pizza-muzzarella.webp',
    price: 11490,
    oldPrice: 12790,
    stock: 10,
    available: true,
    featured: false,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: '1 grande + gaseosa 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },

  // ===== Promos =====
  {
    id: 'p-promo-dia',
    name: 'Promo del día: 2 pizzas grandes + gaseosa',
    description: '2 pizzas grandes a elección y gaseosa 1.5 L. La promo de la maqueta, lista para vender.',
    categoryId: 'promos',
    tone: 'promo',
    image: 'assets/products/promo-dia.webp',
    price: 19990,
    oldPrice: 23980,
    stock: 8,
    available: true,
    featured: true,
    popular: true,
    combo: true,
    badge: 'Promo del día',
    unit: 'promo',
    unitLabel: '2 grandes + gaseosa 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 28,
  },
  {
    id: 'p-promo-muzza-x2',
    name: 'Promo 2 muzzarellas',
    description: 'Dos muzzarella grandes para compartir, pensadas para el finde.',
    categoryId: 'promos',
    tone: 'promo',
    image: 'assets/products/pizza-muzzarella.webp',
    price: 15990,
    oldPrice: 17980,
    stock: 9,
    available: true,
    featured: true,
    combo: true,
    badge: 'Promo',
    unit: 'promo',
    unitLabel: '2 grandes de muzzarella',
    marketNote: MARKET_NOTE,
    prepMinutes: 26,
  },

  // ===== Bebidas =====
  {
    id: 'p-coca',
    name: 'Coca-Cola 1.5L',
    description: 'Gaseosa bien fría para acompañar la pizza.',
    categoryId: 'bebidas',
    tone: 'drink',
    image: 'assets/products/bebida-cola.webp',
    price: 2900,
    stock: 20,
    available: true,
    featured: false,
    popular: true,
    unit: 'unidad',
    unitLabel: 'Botella 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
  {
    id: 'p-sprite',
    name: 'Sprite 1.5L',
    description: 'Lima-limón bien fría, opción liviana para la mesa.',
    categoryId: 'bebidas',
    tone: 'drink',
    price: 2700,
    stock: 14,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Botella 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
  {
    id: 'p-agua',
    name: 'Agua mineral',
    description: 'Agua mineral sin gas, opción liviana para acompañar.',
    categoryId: 'bebidas',
    tone: 'drink',
    price: 1600,
    stock: 0,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Botella 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
];

export const seedOrders = [
  {
    id: 'LT-0001',
    customerName: 'Juan Pérez',
    customerPhone: '2990000000',
    address: 'Av. San Martín 1234, Neuquén',
    addressDetails: {
      streetLine: 'Av. San Martín 1234',
      neighborhood: 'Neuquén centro',
      reference: 'Tocar timbre',
      label: 'Av. San Martín 1234, Neuquén centro',
    },
    deliveryMode: 'delivery',
    paymentMethod: 'Efectivo',
    notes: 'Tocar timbre. Cambio con $30000.',
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    status: 'delivered',
    items: [
      { productId: 'p-muzzarella', name: 'Muzzarella', icon: '', quantity: 1, unitPrice: 8990, unit: 'unidad' },
      { productId: 'p-pepperoni', name: 'Pepperoni', icon: '', quantity: 1, unitPrice: 11490, unit: 'unidad' },
      { productId: 'p-coca', name: 'Coca-Cola 1.5L', icon: '', quantity: 1, unitPrice: 2900, unit: 'unidad' },
    ],
    subtotal: 23380,
    deliveryFee: 1990,
    total: 25370,
    statusHistory: [
      { status: 'received', at: new Date(Date.now() - 1000 * 60 * 22).toISOString() },
      { status: 'preparing', at: new Date(Date.now() - 1000 * 60 * 16).toISOString() },
      { status: 'ready', at: new Date(Date.now() - 1000 * 60 * 12).toISOString() },
      { status: 'on_the_way', at: new Date(Date.now() - 1000 * 60 * 8).toISOString() },
      { status: 'delivered', at: new Date(Date.now() - 1000 * 60 * 2).toISOString() },
    ],
    // Pedido de ejemplo: sin reputación inventada del repartidor (rating/viajes),
    // sólo los datos operativos que la demo realmente registra.
    delivery: {
      driverName: 'Martín',
      driverPhone: '2991112233',
      estimatedMinutes: 0,
      currentLocationLabel: 'Pedido entregado',
      deliveredAt: new Date(Date.now() - 1000 * 60 * 2).toISOString(),
    },
  },
];
