// Catálogo de demostración de La Taba.
// Precios en ARS, estimados de mercado argentino y editables desde el panel.
// Los `tone` controlan el bloque tonal sobrio del thumbnail (ver styles.css).
//
// Categorías:
//  - `demo: true`    → categoría configurable por el comercio (puede ocultarse/editar).
//  - `pickup: true`  → pensada para retiro en local.
// Nota legal: no se incluyen bebidas alcohólicas. "Bebidas" y "Gaseosas" son
// categorías seguras. Una eventual categoría "Alcohol" debe quedar como demo
// configurable y editable por el comercio (ver README), nunca con ventas falsas.
export const categories = [
  { id: 'all', name: 'Todos' },
  { id: 'promos', name: 'Promos' },
  { id: 'combos', name: 'Combos' },
  { id: 'carnes', name: 'Carnes' },
  { id: 'pollos', name: 'Pollos' },
  { id: 'achuras', name: 'Achuras' },
  { id: 'embutidos', name: 'Embutidos' },
  { id: 'gaseosas', name: 'Gaseosas' },
  { id: 'bebidas', name: 'Bebidas' },
  { id: 'lacteos', name: 'Lácteos', demo: true },
  { id: 'almacen', name: 'Almacén' },
  { id: 'retiro', name: 'Retiro en local', pickup: true },
];

const MARKET_NOTE = 'Precio estimado de mercado, editable desde el panel.';

export const products = [
  // ===== Promos =====
  {
    id: 'p-viernes-parrilla',
    name: 'Promo viernes de parrilla',
    description: 'Selección de cortes y achuras para encarar el finde como corresponde.',
    categoryId: 'promos',
    tone: 'promo',
    price: 29900,
    oldPrice: 34900,
    stock: 5,
    available: true,
    featured: true,
    popular: true,
    combo: true,
    badge: 'Promo del día',
    unit: 'promo',
    unitLabel: 'Para 4 a 6 personas',
    marketNote: MARKET_NOTE,
    prepMinutes: 32,
  },
  {
    id: 'p-promo-milanesas',
    name: 'Promo milanesas + bebida',
    description: 'Milanesas de carne listas para freír con una gaseosa fría incluida.',
    categoryId: 'promos',
    tone: 'promo',
    price: 8900,
    oldPrice: 10400,
    stock: 9,
    available: true,
    featured: true,
    popular: true,
    badge: 'Promo',
    unit: 'promo',
    unitLabel: '1 kg milanesas + bebida',
    marketNote: MARKET_NOTE,
    prepMinutes: 16,
  },

  // ===== Combos =====
  {
    id: 'p-combo-familiar',
    name: 'Combo asado familiar',
    description: 'Asado, chorizos y morcilla para una parrilla completa de fin de semana.',
    categoryId: 'combos',
    tone: 'combo',
    price: 24990,
    oldPrice: 29000,
    stock: 6,
    available: true,
    featured: true,
    popular: true,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: '1 kg asado + chorizos + morcilla',
    marketNote: MARKET_NOTE,
    prepMinutes: 30,
  },
  {
    id: 'p-combo-parrillero',
    name: 'Combo parrillero',
    description: 'Mix de chorizos, morcilla y provoleta listo para encender el fuego.',
    categoryId: 'combos',
    tone: 'combo',
    price: 12490,
    oldPrice: 14200,
    stock: 8,
    available: true,
    featured: true,
    popular: true,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: '1 kg surtido',
    marketNote: MARKET_NOTE,
    prepMinutes: 22,
  },
  {
    id: 'p-combo-milanesas',
    name: 'Combo milanesas',
    description: 'Milanesas de carne y de pollo para resolver la semana sin vueltas.',
    categoryId: 'combos',
    tone: 'combo',
    price: 11900,
    oldPrice: 13500,
    stock: 10,
    available: true,
    featured: false,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: '1 kg carne + 1 kg pollo',
    marketNote: MARKET_NOTE,
    prepMinutes: 18,
  },
  {
    id: 'p-combo-dos',
    name: 'Combo para dos',
    description: 'Selección equilibrada para una cena de a dos con buena carne.',
    categoryId: 'combos',
    tone: 'combo',
    price: 14500,
    oldPrice: 16900,
    stock: 8,
    available: true,
    featured: false,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: 'Para 2 personas',
    marketNote: MARKET_NOTE,
    prepMinutes: 24,
  },

  // ===== Carnes =====
  {
    id: 'p-asado-especial',
    name: 'Asado especial',
    description: 'Tira de asado seleccionada, buen punto de grasa para parrilla lenta.',
    categoryId: 'carnes',
    tone: 'beef',
    price: 9800,
    oldPrice: 11200,
    stock: 12,
    available: true,
    featured: true,
    popular: true,
    badge: 'Más pedido',
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },
  {
    id: 'p-vacio',
    name: 'Vacío especial',
    description: 'Vacío tierno y parejo, ideal para horno o parrilla. Corte estrella del finde.',
    categoryId: 'carnes',
    tone: 'beef',
    price: 11200,
    oldPrice: 12800,
    stock: 7,
    available: true,
    featured: true,
    popular: true,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 25,
  },
  {
    id: 'p-asado-tira',
    name: 'Asado de tira',
    description: 'Corte clásico de tira para la parrilla de todos los días.',
    categoryId: 'carnes',
    tone: 'beef',
    price: 8600,
    stock: 14,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 18,
  },
  {
    id: 'p-tapa-asado',
    name: 'Tapa de asado',
    description: 'Corte sabroso y económico, ideal para cocción lenta a la parrilla.',
    categoryId: 'carnes',
    tone: 'beef',
    price: 8200,
    stock: 10,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 22,
  },
  {
    id: 'p-entrana',
    name: 'Entraña',
    description: 'Entraña fina y jugosa, lista para sellar rápido y servir.',
    categoryId: 'carnes',
    tone: 'beef',
    price: 13900,
    stock: 6,
    available: true,
    featured: false,
    popular: true,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 16,
  },
  {
    id: 'p-matambre',
    name: 'Matambre',
    description: 'Matambre fresco, recomendado para pizza a la parrilla o relleno.',
    categoryId: 'carnes',
    tone: 'beef',
    price: 8900,
    stock: 4,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 18,
  },
  {
    id: 'p-bondiola',
    name: 'Bondiola de cerdo',
    description: 'Bondiola jugosa para horno, parrilla o cocción lenta.',
    categoryId: 'carnes',
    tone: 'beef',
    price: 7400,
    stock: 9,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },

  // ===== Pollos =====
  {
    id: 'p-pollo-entero',
    name: 'Pollo entero',
    description: 'Pollo fresco entero, listo para horno o parrilla.',
    categoryId: 'pollos',
    tone: 'chicken',
    price: 5200,
    stock: 12,
    available: true,
    featured: true,
    unit: 'unidad',
    unitLabel: '1 pollo (aprox. 1,8 kg)',
    marketNote: MARKET_NOTE,
    prepMinutes: 15,
  },
  {
    id: 'p-pollo-trozado',
    name: 'Pollo trozado',
    description: 'Pollo fresco trozado, práctico para horno, parrilla o guiso.',
    categoryId: 'pollos',
    tone: 'chicken',
    price: 5600,
    stock: 10,
    available: true,
    featured: false,
    popular: true,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 12,
  },
  {
    id: 'p-pata-muslo',
    name: 'Pata muslo',
    description: 'Pata muslo de pollo fresco, jugosa y rendidora.',
    categoryId: 'pollos',
    tone: 'chicken',
    price: 4800,
    stock: 14,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 12,
  },
  {
    id: 'p-pechuga',
    name: 'Pechuga de pollo',
    description: 'Pechuga magra y fresca, ideal para milanesas o plancha.',
    categoryId: 'pollos',
    tone: 'chicken',
    price: 6200,
    stock: 11,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 10,
  },

  // ===== Achuras =====
  {
    id: 'p-morcilla',
    name: 'Morcilla',
    description: 'Morcilla criolla para abrir la parrilla. Sabor de carnicería.',
    categoryId: 'achuras',
    tone: 'achura',
    price: 3600,
    stock: 11,
    available: true,
    featured: false,
    popular: true,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 10,
  },
  {
    id: 'p-chinchulin',
    name: 'Chinchulín',
    description: 'Chinchulín fresco y limpio, crocante a fuego lento.',
    categoryId: 'achuras',
    tone: 'achura',
    price: 4200,
    stock: 7,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 14,
  },
  {
    id: 'p-molleja',
    name: 'Molleja',
    description: 'Molleja de primera, dorada y crocante para arrancar el asado.',
    categoryId: 'achuras',
    tone: 'achura',
    price: 9800,
    stock: 5,
    available: true,
    featured: true,
    popular: true,
    badge: 'Más pedido',
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 16,
  },

  // ===== Embutidos =====
  {
    id: 'p-chorizo-parrillero',
    name: 'Chorizo parrillero',
    description: 'Chorizo clásico para parrilla, buen punto de grasa y condimento.',
    categoryId: 'embutidos',
    tone: 'sausage',
    price: 4300,
    stock: 3,
    available: true,
    featured: false,
    popular: true,
    unit: 'kg',
    unitLabel: '1 kg (5 a 6 unidades)',
    marketNote: MARKET_NOTE,
    prepMinutes: 12,
  },
  {
    id: 'p-chorizo-colorado',
    name: 'Chorizo colorado',
    description: 'Chorizo colorado estacionado, ideal para picada o cocido.',
    categoryId: 'embutidos',
    tone: 'sausage',
    price: 5200,
    stock: 8,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 8,
  },
  {
    id: 'p-salchicha-parrillera',
    name: 'Salchicha parrillera',
    description: 'Salchicha parrillera fresca, lista para el pan o la guarnición.',
    categoryId: 'embutidos',
    tone: 'sausage',
    price: 3900,
    stock: 12,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 10,
  },

  // ===== Gaseosas =====
  {
    id: 'p-coca',
    name: 'Coca-Cola 2.25L',
    description: 'Gaseosa bien fría para acompañar el pedido.',
    categoryId: 'gaseosas',
    tone: 'drink',
    price: 2800,
    stock: 20,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Botella 2.25 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
  {
    id: 'p-sprite',
    name: 'Sprite 2.25L',
    description: 'Lima-limón bien fría, opción liviana para la mesa.',
    categoryId: 'gaseosas',
    tone: 'drink',
    price: 2700,
    stock: 14,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Botella 2.25 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },

  // ===== Bebidas =====
  {
    id: 'p-agua',
    name: 'Agua mineral',
    description: 'Agua mineral sin gas, opción liviana para acompañar.',
    categoryId: 'bebidas',
    tone: 'drink',
    price: 1600,
    stock: 0,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Botella 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
  {
    id: 'p-soda',
    name: 'Soda sifón',
    description: 'Soda fría para la mesa, clásico de cualquier asado.',
    categoryId: 'bebidas',
    tone: 'drink',
    price: 1800,
    stock: 16,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Sifón 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },

  // ===== Lácteos (categoría demo configurable) =====
  {
    id: 'p-provoleta',
    name: 'Provoleta',
    description: 'Provoleta fresca para la parrilla, dorada por fuera y cremosa adentro.',
    categoryId: 'lacteos',
    tone: 'dairy',
    price: 4200,
    stock: 13,
    available: true,
    featured: false,
    popular: true,
    unit: 'unidad',
    unitLabel: '1 unidad',
    marketNote: MARKET_NOTE,
    prepMinutes: 6,
  },
  {
    id: 'p-queso-cremoso',
    name: 'Queso cremoso',
    description: 'Horma de queso cremoso para la picada o la cocina.',
    categoryId: 'lacteos',
    tone: 'dairy',
    price: 6800,
    stock: 9,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 3,
  },

  // ===== Almacén =====
  {
    id: 'p-carbon',
    name: 'Carbón 3 kg',
    description: 'Bolsa de carbón para encender el fuego sin vueltas.',
    categoryId: 'almacen',
    tone: 'pantry',
    price: 3500,
    stock: 22,
    available: true,
    featured: false,
    popular: true,
    unit: 'bolsa',
    unitLabel: 'Bolsa 3 kg',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
  {
    id: 'p-pan-casero',
    name: 'Pan casero',
    description: 'Pan casero del día para acompañar la picada o el choripán.',
    categoryId: 'almacen',
    tone: 'pantry',
    price: 2200,
    stock: 15,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: '1 unidad',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
  {
    id: 'p-chimichurri',
    name: 'Chimichurri casero',
    description: 'Chimichurri casero en frasco, condimento clásico de parrilla.',
    categoryId: 'almacen',
    tone: 'pantry',
    price: 2600,
    stock: 18,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Frasco 250 g',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },

  // ===== Retiro en local =====
  {
    id: 'p-combo-retiro',
    name: 'Combo retiro local',
    description: 'Pack pensado para retirar por el local con precio preferencial.',
    categoryId: 'retiro',
    tone: 'combo',
    price: 9990,
    oldPrice: 11500,
    stock: 10,
    available: true,
    featured: true,
    combo: true,
    badge: 'Retiro',
    unit: 'combo',
    unitLabel: 'Solo retiro en local',
    marketNote: MARKET_NOTE,
    prepMinutes: 15,
  },
  {
    id: 'p-pack-retiro-express',
    name: 'Pack retiro express',
    description: 'Cortes listos para retirar en minutos, ideal para el apuro.',
    categoryId: 'retiro',
    tone: 'combo',
    price: 7490,
    stock: 8,
    available: true,
    featured: false,
    badge: 'Retiro',
    unit: 'pack',
    unitLabel: 'Listo para retirar',
    marketNote: MARKET_NOTE,
    prepMinutes: 10,
  },
];

export const seedOrders = [
  {
    id: 'LT-0001',
    customerName: 'Juan Pérez',
    customerPhone: '2990000000',
    address: 'Av. San Martín 1234, Neuquén',
    deliveryMode: 'delivery',
    paymentMethod: 'Efectivo',
    notes: 'Tocar timbre. Cambio con $30000.',
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    status: 'preparing',
    items: [
      { productId: 'p-vacio', name: 'Vacío especial', icon: '', quantity: 1, unitPrice: 11200, unit: 'kg' },
      { productId: 'p-chorizo-parrillero', name: 'Chorizo parrillero', icon: '', quantity: 1, unitPrice: 4300, unit: 'kg' },
      { productId: 'p-coca', name: 'Coca-Cola 2.25L', icon: '', quantity: 1, unitPrice: 2800, unit: 'unidad' },
    ],
    subtotal: 18300,
    deliveryFee: 1990,
    total: 20290,
    statusHistory: [
      { status: 'received', at: new Date(Date.now() - 1000 * 60 * 22).toISOString() },
      { status: 'preparing', at: new Date(Date.now() - 1000 * 60 * 16).toISOString() },
    ],
    delivery: {
      driverName: 'Martín',
      driverPhone: '2991112233',
      driverRating: 4.9,
      driverTrips: 128,
      estimatedMinutes: 18,
      distanceKm: 1.2,
      currentLocationLabel: 'En el local esperando salida',
    },
  },
];
