// Catálogo de demostración de La Taba.
// Precios en ARS, estimados de mercado argentino y editables desde el panel.
// Nota: los `tone` controlan el gradiente del thumbnail premium (ver styles.css).
export const categories = [
  { id: 'all', name: 'Todos', icon: '🔥' },
  { id: 'carnes', name: 'Carnes', icon: '🥩' },
  { id: 'combos', name: 'Combos', icon: '📦' },
  { id: 'milanesas', name: 'Milanesas', icon: '🍽️' },
  { id: 'chorizos', name: 'Embutidos', icon: '🌶️' },
  { id: 'hamburguesas', name: 'Hamburguesas', icon: '🍔' },
  { id: 'pollos', name: 'Pollos', icon: '🍗' },
  { id: 'bebidas', name: 'Bebidas', icon: '🥤' },
  { id: 'promos', name: 'Promos', icon: '⭐' },
];

const MARKET_NOTE = 'Precio estimado de mercado, editable desde el panel.';

export const products = [
  {
    id: 'p-asado-especial',
    name: 'Asado especial',
    description: 'Tira de asado seleccionada, buen punto de grasa para parrilla lenta.',
    categoryId: 'carnes',
    icon: '🥩',
    tone: 'beef',
    price: 9800,
    oldPrice: 11200,
    stock: 12,
    available: true,
    featured: true,
    popular: true,
    badge: 'Más pedido',
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },
  {
    id: 'p-vacio',
    name: 'Vacío especial',
    description: 'Vacío tierno y parejo, ideal para horno o parrilla. Corte estrella del finde.',
    categoryId: 'carnes',
    icon: '🥩',
    tone: 'beef',
    price: 11200,
    oldPrice: 12800,
    stock: 7,
    available: true,
    featured: true,
    popular: true,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 25,
  },
  {
    id: 'p-asado-tira',
    name: 'Asado de tira',
    description: 'Corte clásico de tira para la parrilla de todos los días.',
    categoryId: 'carnes',
    icon: '🥩',
    tone: 'beef',
    price: 8600,
    stock: 14,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 18,
  },
  {
    id: 'p-matambre',
    name: 'Matambre',
    description: 'Matambre fresco, recomendado para pizza a la parrilla o relleno.',
    categoryId: 'carnes',
    icon: '🥓',
    tone: 'beef',
    price: 8900,
    stock: 4,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 18,
  },
  {
    id: 'p-bondiola',
    name: 'Bondiola de cerdo',
    description: 'Bondiola jugosa para horno, parrilla o cocción lenta.',
    categoryId: 'carnes',
    icon: '🍖',
    tone: 'beef',
    price: 7400,
    stock: 9,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 20,
  },
  {
    id: 'p-combo-familiar',
    name: 'Combo asado familiar',
    description: 'Asado, chorizos y morcilla para una parrilla completa de fin de semana.',
    categoryId: 'combos',
    icon: '📦',
    tone: 'combo',
    price: 24990,
    oldPrice: 29000,
    stock: 6,
    available: true,
    featured: true,
    popular: true,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: '1 kg asado + chorizos + morcilla',
    marketNote: MARKET_NOTE,
    prepMinutes: 30,
  },
  {
    id: 'p-combo-parrillero',
    name: 'Combo parrillero',
    description: 'Mix de chorizos, morcilla y provoleta listo para encender el fuego.',
    categoryId: 'combos',
    icon: '📦',
    tone: 'combo',
    price: 12490,
    oldPrice: 14200,
    stock: 8,
    available: true,
    featured: true,
    popular: true,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: '1 kg surtido',
    marketNote: MARKET_NOTE,
    prepMinutes: 22,
  },
  {
    id: 'p-combo-dos',
    name: 'Combo para dos',
    description: 'Selección equilibrada para una cena de a dos con buena carne.',
    categoryId: 'combos',
    icon: '📦',
    tone: 'combo',
    price: 14500,
    oldPrice: 16900,
    stock: 8,
    available: true,
    featured: true,
    combo: true,
    badge: 'Combo',
    unit: 'combo',
    unitLabel: 'Para 2 personas',
    marketNote: MARKET_NOTE,
    prepMinutes: 24,
  },
  {
    id: 'p-combo-retiro',
    name: 'Combo retiro local',
    description: 'Pack pensado para retirar por el local con precio preferencial.',
    categoryId: 'combos',
    icon: '🏪',
    tone: 'combo',
    price: 9990,
    oldPrice: 11500,
    stock: 10,
    available: true,
    featured: false,
    combo: true,
    badge: 'Retiro',
    unit: 'combo',
    unitLabel: 'Solo retiro en local',
    marketNote: MARKET_NOTE,
    prepMinutes: 15,
  },
  {
    id: 'p-milanesa-carne',
    name: 'Milanesas listas para freír',
    description: 'Milanesas de carne con rebozado clásico, listas para cocinar.',
    categoryId: 'milanesas',
    icon: '🍽️',
    tone: 'mila',
    price: 6400,
    stock: 18,
    available: true,
    featured: true,
    popular: true,
    badge: 'Más pedido',
    unit: 'kg',
    unitLabel: '6 unidades aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 15,
  },
  {
    id: 'p-milanesa-pollo',
    name: 'Milanesa de pollo',
    description: 'Milanesas de pollo frescas, prácticas para resolver la comida.',
    categoryId: 'milanesas',
    icon: '🍗',
    tone: 'mila',
    price: 5800,
    stock: 15,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '6 unidades aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 15,
  },
  {
    id: 'p-chorizo-parrillero',
    name: 'Chorizo parrillero',
    description: 'Chorizo clásico para parrilla, buen punto de grasa y condimento.',
    categoryId: 'chorizos',
    icon: '🌭',
    tone: 'sausage',
    price: 4300,
    stock: 3,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg (5 a 6 unidades)',
    marketNote: MARKET_NOTE,
    prepMinutes: 12,
  },
  {
    id: 'p-morcilla',
    name: 'Morcilla',
    description: 'Morcilla criolla para abrir la parrilla. Sabor de carnicería.',
    categoryId: 'chorizos',
    icon: '🩸',
    tone: 'sausage',
    price: 3600,
    stock: 11,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 kg aprox.',
    marketNote: MARKET_NOTE,
    prepMinutes: 10,
  },
  {
    id: 'p-provoleta',
    name: 'Provoleta',
    description: 'Provoleta fresca para la parrilla, dorada por fuera y cremosa adentro.',
    categoryId: 'chorizos',
    icon: '🧀',
    tone: 'mila',
    price: 4200,
    stock: 13,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: '1 unidad',
    marketNote: MARKET_NOTE,
    prepMinutes: 8,
  },
  {
    id: 'p-hamburguesa-casera',
    name: 'Hamburguesas caseras',
    description: 'Medallones artesanales para plancha o parrilla, pack por 4 unidades.',
    categoryId: 'hamburguesas',
    icon: '🍔',
    tone: 'beef',
    price: 5200,
    oldPrice: 6000,
    stock: 9,
    available: true,
    featured: true,
    unit: 'pack x4',
    unitLabel: '4 unidades',
    marketNote: MARKET_NOTE,
    prepMinutes: 12,
  },
  {
    id: 'p-pollo-entero',
    name: 'Pollo trozado',
    description: 'Pollo fresco trozado, listo para horno, parrilla o guiso.',
    categoryId: 'pollos',
    icon: '🍗',
    tone: 'chicken',
    price: 5600,
    stock: 10,
    available: true,
    featured: false,
    unit: 'kg',
    unitLabel: '1 pollo (aprox. 1,8 kg)',
    marketNote: MARKET_NOTE,
    prepMinutes: 18,
  },
  {
    id: 'p-coca',
    name: 'Coca-Cola 2.25L',
    description: 'Gaseosa bien fría para acompañar el pedido.',
    categoryId: 'bebidas',
    icon: '🥤',
    tone: 'drink',
    price: 2800,
    stock: 20,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Botella 2.25 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 3,
  },
  {
    id: 'p-agua',
    name: 'Agua mineral',
    description: 'Agua mineral sin gas, opción liviana para acompañar.',
    categoryId: 'bebidas',
    icon: '💧',
    tone: 'drink',
    price: 1600,
    stock: 0,
    available: true,
    featured: false,
    unit: 'unidad',
    unitLabel: 'Botella 1.5 L',
    marketNote: MARKET_NOTE,
    prepMinutes: 2,
  },
  {
    id: 'p-viernes-parrilla',
    name: 'Promo viernes de parrilla',
    description: 'Selección de cortes y chorizos para encarar el finde como corresponde.',
    categoryId: 'promos',
    icon: '🔥',
    tone: 'promo',
    price: 29900,
    oldPrice: 34900,
    stock: 5,
    available: true,
    featured: true,
    combo: true,
    badge: 'Promo del día',
    unit: 'promo',
    unitLabel: 'Para 4 a 6 personas',
    marketNote: MARKET_NOTE,
    prepMinutes: 32,
  },
];

export const seedOrders = [
  {
    id: 'LT-0001',
    customerName: 'Juan Pérez',
    customerPhone: '2990000000',
    address: 'Av. San Martín 1234, Neuquén',
    deliveryMode: 'delivery',
    paymentMethod: 'Efectivo',
    notes: 'Tocar timbre. Cambio con $30000.',
    createdAt: new Date(Date.now() - 1000 * 60 * 22).toISOString(),
    status: 'preparing',
    items: [
      { productId: 'p-vacio', name: 'Vacío especial', icon: '🥩', quantity: 1, unitPrice: 11200, unit: 'kg' },
      { productId: 'p-chorizo-parrillero', name: 'Chorizo parrillero', icon: '🌭', quantity: 1, unitPrice: 4300, unit: 'kg' },
      { productId: 'p-coca', name: 'Coca-Cola 2.25L', icon: '🥤', quantity: 1, unitPrice: 2800, unit: 'unidad' },
    ],
    subtotal: 18300,
    deliveryFee: 1990,
    total: 20290,
    statusHistory: [
      { status: 'received', at: new Date(Date.now() - 1000 * 60 * 22).toISOString() },
      { status: 'preparing', at: new Date(Date.now() - 1000 * 60 * 16).toISOString() },
    ],
    delivery: {
      driverName: 'Martín',
      driverPhone: '2991112233',
      driverRating: 4.9,
      driverTrips: 128,
      estimatedMinutes: 18,
      distanceKm: 1.2,
      currentLocationLabel: 'En el local esperando salida',
    },
  },
];
